name: CI first code check

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for manually running CI first code check workflow
        required: False
        default: ''

jobs:

  first_check:
    name: first code check / python-3.12 / ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
          enable-cache: true
          cache-suffix: first-check
      - name: Show environment info
        run: |
          which uv
          uv --version
          uv run python --version
      - name: Install dependencies
        run: uv sync --frozen
      - name: Show packages
        run: uv pip list
      - name: Run ruff linter
        run: uv run ruff check --output-format=github
      - name: Test with coverage
        run: uv run pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
      - name: Correct coverage paths
        run: sed -i "s+$PWD/++g" coverage.xml
      - name: Store PR metadata in json file
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          jq -n --arg pr_number "$PR_NUMBER"\
                  --arg head_ref "$HEAD_REF"\
                  --arg base_ref "$BASE_REF"\
                  '{"pr_number": $pr_number, "head_ref": $head_ref, "base_ref": $base_ref}' > pr_metadata.json
      - uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-data-pip
          path: |
            coverage.xml
            xunit-result.xml
            pr_metadata.json
