name: Anaconda Build

on: [push, pull_request]

jobs:

  build:
    name: ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-build
          auto-activate-base: false
          auto-update-conda: true
          environment-file: conda/environment-build.yml
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Build the conda package
        shell: bash -l {0}
        run: |
          conda config --set anaconda_upload no
          export BUILD_FOLDER=/tmp/matchms/_build
          mkdir -p $BUILD_FOLDER
          conda build --numpy 1.18.1 --no-include-recipe \
            --channel bioconda --channel conda-forge \
            --croot $BUILD_FOLDER \
            ./conda
